drop trigger if exists updating_issue_triggerM on borrowinfoformember;
drop trigger if exists updating_issue_triggerE on borrowinfoforEmployee;
drop function if exists update_issue_trigg_function();
drop trigger if exists updating_claim_trigger on claim;
drop function if exists update_claim_trigg_function();
drop trigger if exists updating_rating_trigger on rate;
drop function if exists update_rating_trigg_function();
drop trigger if exists updating_returnH_trigger on returnhistoryinfo;
drop function if exists update_returnH_trigg_function();
drop table if exists claim;
drop table if exists rate;
drop table if exists ReturnHistoryInfo;
drop table if exists JournalsInfo;
drop table if exists BorrowInfoForEmployee;
drop table if exists EmployeeInfo;
drop table if exists BorrowInfoForMember;
drop table if exists DiscussionForumInfo;
drop table if exists RecommendBookInfo;
drop table if exists BooksInfo;
drop table if exists MembersInfo;
drop type if exists Reference;
drop type if exists AName;
